<a href="https://colab.research.google.com/github/eoooomji/home_python/blob/master/python_08_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## 3차원 이상에서 차원 구분법

In [2]:
# 0부터 24미만까지 생성
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [3]:
# print하면 array라는 글자는 안보인다.
# 공백은 그대로 보인다. -> 차원 구분이 가능하다.
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [4]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
b[0, 1]

array([4, 5, 6, 7])

In [6]:
b[1, 1]

array([16, 17, 18, 19])

In [7]:
b[0, 1, 3]

7

## fancy indexing과 indexing의 차이

- indexing은 원래 차원에서 하나 감소해서 가져온다.

- fancy indexing은 원래 차원에서 그대로 가져온다.

In [8]:
# indexing은 차원이 하나 감소한다.(3차원 > 2차원)
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
# fancy indexing은 원래 차원 그대로 가져온다.
b[[0]]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [10]:
# b[0]은 b[0, :, :]의 단축 표현이다.
b[[0], :, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [12]:
# b의 0번째 공간, 1번째 행 미만, 열 전체
b[[0], : 1, :]

array([[[0, 1, 2, 3]]])

## Ellipsis

- ...(Ellipsis)는 이후로 모든 것을 의미한다.


In [13]:
type(...)

ellipsis

In [14]:
b[0, :, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
b[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
print(b[0]) # 생략기법
print(b[0, :, :]) # slicing 기법
print(b[0, ...]) # Ellipsis 기법

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
# 숫자 1, 5, 9 가져오기
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [18]:
b[0, :, 1]

array([1, 5, 9])

In [19]:
# 숫자 1, 5, 9, 3, 7, 11 가져오기
b[0, ...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
b[0, :, [1, 3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [21]:
print(b[0, :, [1, 3]])

[[ 1  5  9]
 [ 3  7 11]]


In [22]:
# 숫자 4, 5, 6, 7, 16, 17, 18, 19 가져오기
b[:, 1, :]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [23]:
b[:, 1:2, :]

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [27]:
# 숫자 3, 7, 11, 15, 19, 23 가져오기
print(b[:, :, 3])
print('============')
print(b[:, :, 3:])
print('============')
print(b[:, :, -1])
print('============')
print(b[:, :, [3]])

[[ 3  7 11]
 [15 19 23]]
[[[ 3]
  [ 7]
  [11]]

 [[15]
  [19]
  [23]]]
[[ 3  7 11]
 [15 19 23]]
[[[ 3]
  [ 7]
  [11]]

 [[15]
  [19]
  [23]]]


In [28]:
c = b[:, :, 3]
c.shape
c

array([[ 3,  7, 11],
       [15, 19, 23]])

## 줄임표현

- 출력해야 할 데이터 수가 엄청 클 때 보이는 ... 은 Ellipsis와는 다르다.

In [29]:
# out에 나오는 ... 은 단순한 줄임표현이다.
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [31]:
# 앞 뒤로 6개의 값이 더 나온다.
np.set_printoptions(edgeitems = 6)
np.arange(100000)

array([    0,     1,     2,     3,     4,     5, ..., 99994, 99995, 99996,
       99997, 99998, 99999])

## 연산

- numpy연산의 기본은 두 개의 shape이 같아야 한다.

In [32]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a.shape

(3, 4)

In [34]:
b = np.arange(1, 13).reshape(3, 4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
b.shape

(3, 4)

numpy는 elementwise로 vectorize 연산을 한다.

vectorize는 데이터의 연산을 일관적으로 처리하는 기능이다.

In [36]:
# 같은 위치의 원소끼리 더해준다.(elements)
a + b

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [37]:
# python의 list에서 연산자는 elementwise가 아니라 list를 확장시킨다.(연결)
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [39]:
@np.vectorize
def plus(a, b) :
  return a + b

plus([1, 2, 3,], [4, 5, 6]) # elementwise, vectorize

array([5, 7, 9])

In [40]:
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
b = np.arange(6, 12).reshape(2, 3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [42]:
a * b # elementwise

array([[ 0,  7, 16],
       [27, 40, 55]])

In [43]:
# python의 list끼리 * (곱하기)를 할 수 없다.
[1, 2, 3] * [4, 5, 6]

TypeError: ignored