<a href="https://colab.research.google.com/github/eoooomji/home_python/blob/master/python_07_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## Numpy 정의

- Numpy는 Numbercal python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지 중 하나이다.

- 과학 계산을 위한 대부분의 패키지는 Numpy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.

- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드 캐스팅 기능을 제공한다.

- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.

- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적대된 파일을 다루는 도구이다.

- 선형대수, 난수 생성기 등에 사용한다.

- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.

- numpy는 8바이트이다.(64비트)

공식 문서

https://numpy.org/doc/stable/

numpy 100 문제

https://github.com/rougier/numpy-100

## 1. 데이터 생성

In [2]:
# !pip install numpy
import numpy as np

In [ ]:
# 1차원 배열 = 벡터
a = np.zeros(3) 
a

array([0., 0., 0.])

In [ ]:
print(a)
print(type(a))
print(dir(a))

[0. 0. 0.]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__re

In [ ]:
# 1차원 배열 = 벡터
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
print(a)
print(type(a))
print(dir(a))
print(len(dir(a)))

[1 2 3]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr_

In [ ]:
 # 2차원 배열 = 행렬
 b = np.array([[1, 2], [3, 4]])
 b

array([[1, 2],
       [3, 4]])

In [ ]:
print(b)
print(type(b))
print(dir(b))
print(len(dir(b)))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '

In [ ]:
# 3차원 이상 배열 = 텐서(tensor)
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
print(c)
print(type(c))
print(dir(c))
print(len(dir(c)))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__

In [ ]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous 이다. numpy는 배열이며 안의 데이터는 같은 동일 취급이 된다.
a = np.array([1, '2', 3])
print(a)
print(type(a))
print(type(a[0]))

['1' '2' '3']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [ ]:
b = np.array(['a', 1, True])
print(b)
print(type(b))

['a' '1' 'True']
<class 'numpy.ndarray'>


In [ ]:
c = np.array([1, True, 2, False])
print(c)
print(type(c))
print(type(c[0]))
print(type(c[1]))

[1 1 2 0]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### np.zeros

- tuple로 인자를 넣으면 그대로 모양을 만든다.

- ( 2, 3 ) : 2행 3열 행렬을 만든다.

- zeros는 기본값으로 0. (실수)로 값을 모두 채운다.

In [ ]:
a = np.zeros([2, 3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
b = np.zeros([2, 3, 2]) # 3차원
b

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

### np.eye

- eye는 단위 행렬

- 숫자만 사용할 수 있다.

In [ ]:
# 인자값이 1개이면 행과 열이 같다.
# 3행 3열 행렬을 생성한다.
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# eye는 행과 열의 크기를 지정할 수 있다.
# 3행 2열 행렬을 생성한다.
b = np.eye(3, 2)
b

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
# 크기(1)이 시작되는 위치를 지정할 수 있다.
c = np.eye(4, k = 0)
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
c = np.eye(4, k = 1)
c

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### np.identity

- 수학에서 단위 행렬은 영어로 identity matrix이다.

- 크기 한개만 지정해서 생성할 수 있다.

In [3]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
# 인자 하나만 지정할 수있다.
b = np.identity(3, 2)
b

TypeError: ignored

### np.full

- 지정한 크기의 배열을 생성하고 채울 값을 지정한다.

In [5]:
# 2행 2열의 행렬을 생성하고 1로 초기화해준다.
a = np.full((2, 2), 1)
a

array([[1, 1],
       [1, 1]])

In [6]:
# 1행 3열의 행렬을 생성하고 4로 초기화 해준다.
b = np.full(3, 4)
b

array([4, 4, 4])

In [7]:
c = np.full((2, 2), [1, 3])
c

array([[1, 3],
       [1, 3]])

In [9]:
d = np.full((2, 2), [[1, 2], [3, 4]])
d

array([[1, 2],
       [3, 4]])

### np.empty

- 배열을 생성하고 초기화를 지정하지 않는다.

- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.

In [10]:
a = np.empty(3)
a

array([1., 1., 1.])

In [11]:
k = np.zeros((2, 3))
k

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# zeros해서 생성한 배열이 있으면 배열의 값을 0으로 채워준다.
b = np.empty((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# 임의의 값이 넘어간다. 의미는 따로 없다.
c = np.empty((2, 5))
c

array([[3.57721235e-316, 1.77863633e-322, 0.00000000e+000,
        0.00000000e+000, 2.14321575e-312],
       [1.39577330e-047, 5.92935883e-038, 5.59008252e-091,
        5.70315526e-066, 8.05663404e-315]])

### np.ones

- 배열의 모든 값을 1. 로 초기화 해준다.

In [14]:
# 1행 3열의 배열 생성 후 모든 값을 1로 채운다.
a = np.ones(3)
a

array([1., 1., 1.])

In [16]:
# b = np.ones((2, 3))
b = np.ones([2, 3])
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
c = np.empty((2, 3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
e = np.eye(3, 4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [19]:
d = np.empty((3, 4))
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [20]:
e = np.full((3, 4), 0)
e

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [21]:
# empty는 값을 지정해 두면 데이터를 그대로 갖고 오지 않는다.
f = np.empty((3, 4))
f

array([[0.00000000e+000, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 8.60952352e-072, 7.78937880e-091,
        1.82751992e+184],
       [8.31638937e-072, 3.50759695e-033, 3.99910963e+252,
        1.46030983e-319]])

### _like

- _like가 붙으면 shape가 같게 만들어진다.

- 연산하기 위해서 shape를 맞춰야하는 경우에 사용한다.

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# 모양을 알기 위해서는 shape 메소드를 이용하면 된다.
a.shape

(2, 3)

In [25]:
b = np.empty_like(a)
b

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [26]:
c = np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

In [27]:
c.shape

(2, 2)

In [28]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
d.shape

(3, 3)

In [30]:
# 모양이 다르기 때문에 연산할 수 없다.
c + d

ValueError: ignored

### linspace

- 동등한 간격으로 값을 생성한다.

- 0부터 49까지 50개가 생성된다면 세번째 num인자 값이 생략되어 있으므로 start와 end를 계산해서 default값이 50이 생성된다.
  
  linspace(start, end, num)  
  linspace(0, 49) # num = 50

In [31]:
a = np.linspace(0, 49)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [32]:
len(a)

50

In [33]:
# 위에 a에서 default값으로 50개가 생성되었으므로 임의의 값이 b에서 50개가 생성되었다.
b = np.linspace(1, 5)
b

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [34]:
len(b)

50

In [35]:
# 1부터 10까지 3개의 요소를 생성한다.
# 기본은 endpoint = True 로 설정되어 있기 때문에 10이 포함된다.
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [36]:
# 1부터 10미만 사이에서 3개의 요소를 생성한다.
# endpoint = False 로 설정되어 있어서 10을 포함하지 않는다.
np.linspace(1, 10, 3, endpoint = False)

array([1., 4., 7.])

### logspace

- linspace와 비슷하다.

- log scale을 사용하는 차이가 있다.

- 1부터 50까지의 사이에 10개의 요소를 생성한다.  
  np.logsapce(1, 50, 10)


In [37]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

### dtype

- numpy는 c언어를 기반으로 해서 만들었기 때문에 c의 데이터 타입을 차용할 수 있다.


In [38]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [39]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [41]:
b = np.array([1, 2, 3], dtype = np.int8)
b

array([1, 2, 3], dtype=int8)

In [42]:
# np.int8은 -128 ~ 127 사이의 값을 저장할 수 있다.
c = np.array([-127, -128, 17, 2, 5, 127], dtype = np.int8)
c

array([-127, -128,   17,    2,    5,  127], dtype=int8)

In [45]:
type(c[0])

numpy.int8

In [46]:
# int는 python의 int를 사용한다.
d = np.array([127, 2, 3, -127, -128], dtype = int)
d

array([ 127,    2,    3, -127, -128])

In [47]:
type(d[0])

numpy.int64

## python 도움말

In [48]:
?sum

In [49]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



## numpy 도움말

In [ ]:
np.lookfor('sum')

In [51]:
a = np.array([[1, 2, 3], [4, 5, 6]])
# array의 shape을 알려준다.
a.shape

(2, 3)

In [52]:
# array가 몇 차원인지 알려준다.
# shape으로도 알 수 있다.
a.ndim

2

In [53]:
# 데이터 타입을 알려준다.
a.dtype

dtype('int64')

In [54]:
# 요소의 개수를 알려준다.
# shaep으로도 알 수 있다.
a.size

6

In [55]:
# 요소당 byte수를 알려준다.
a.itemsize

8

## numpy와 python의 속도차이

- 값이 작을 때는 속도가 비슷하다.

- 값이 커지면 속도 차이가 난다.(numpy를 이용하면 속도가 더 빠름)

In [58]:
np.arange(10) # range와 같음

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
# numpy를 이용한 계산
%time np.sum(np.arange(1000000))

CPU times: user 2.8 ms, sys: 0 ns, total: 2.8 ms
Wall time: 1.98 ms


499999500000

In [66]:
# python을 이용한 계산
%time sum(range(1000000))

CPU times: user 19.8 ms, sys: 0 ns, total: 19.8 ms
Wall time: 19.7 ms


499999500000

In [3]:
%time np.sum(np.arange(1000000000))

CPU times: user 1.07 s, sys: 645 ms, total: 1.71 s
Wall time: 1.72 s


499999999500000000

In [4]:
%time sum(range(1000000000))

CPU times: user 13.7 s, sys: 50.7 ms, total: 13.8 s
Wall time: 13.8 s


499999999500000000

## copy

- 대입문 6가지
  1. a = 1
  
  2. a = b = 1
  
  3. a, b = 1, 2
  
  4. a, *b = 1, 2, 3
  
  5. a += 1

  6. global, nonlocal

### python에서 copy

In [5]:
# heterogeneous, sequence, mutable
a = [1, 2, 3]

b = a

b

[1, 2, 3]

In [6]:
a is b # 메모리 주소 비교

True

In [7]:
# a와 b가 메모리 주소를 공유
# b값을 변경하면 a값도 변한다.
b[0] =7

In [8]:
b

[7, 2, 3]

In [9]:
a

[7, 2, 3]

list copy

In [ ]:
a = [1, 2, 3]

In [10]:
# copy()는 똑같은 값만 갖고 메모리는 공유하지 않는다.
b = a.copy()

In [11]:
a is b

False

In [12]:
id(a)

140391183009984

In [13]:
id(b)

140391182653248

In [14]:
# 값의 비교
a == b

True

In [15]:
b[0] = 9
print(a)
print(b)

[7, 2, 3]
[9, 2, 3]


In [16]:
print(a is b)
print(a == b)

False
False


2차원 list copy

In [17]:
a = [[1, 2, 3]]
a

[[1, 2, 3]]

In [18]:
# shallow copy 발생
b = a.copy()

In [20]:
print(a is b)
print(a == b)
print(id(a))
print(id(b))

False
True
140391183001600
140391181873344


In [21]:
print(a[0] is b[0])
print(a[0] == b[0])

True
True


list deep copy

In [23]:
import copy

In [25]:
a = [[1, 2, 3]]
b = copy.deepcopy(a)

In [26]:
print(a)
print(b)

[[1, 2, 3]]
[[1, 2, 3]]


In [27]:
print(a is b)
print(a == b)
print(a[0] is b[0])
print(a[0] == b[0])

False
True
False
True


슬라이싱 [ : ] (전체라는 뜻)

- 슬라이싱 방식으로 1차 리스트일 때 재할당 시 deepcopy가 발생한다.

- 2차열 리스트 이상인 경우 shallow copy가 발생한다.

In [28]:
a = [1, 2, 3]
b = a[:]
print(b)
print(a is b)
print(a == b)
b[0] = 7
print(a is b)
print(a == b)

[1, 2, 3]
False
True
False
False


In [29]:
# 슬라이싱 2차 이상인 경우 shallow copy가 발생한다.
a = [[1, 2, 3]]
b = a[:]
print(b)
print(a is b)
print(a == b)
b[0][0] = 7
print(a)
print(b)
print(a[0] is b[0])
print(a == b)

[[1, 2, 3]]
False
True
[[7, 2, 3]]
[[7, 2, 3]]
True
True


※ python의 copy는 기본적으로 shallow copy를 한다.

### numpy의 copy

In [30]:
a = b = np.array([1, 2, 3])

In [31]:
print(a is b)
print(a == b)

True
[ True  True  True]


array는 sequence타입으로 인덱싱과 슬라이싱이 가능하다.

In [32]:
a[0] # indexing

1

In [33]:
a[:] # slicing

array([1, 2, 3])

In [34]:
# array는 mutable이다.
# 예외가 몇가지 있지만 mutable에 가깝다.
a[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


array는 homogeneous, sequence, muteable이다.

array deepcopy

In [35]:
a = np.array([[1, 2, 3]])
# numpy는 기본적으로 deepcopy이다.
b = a.copy()

In [36]:
print(a is b)
print(a[0] is b[0])

False
False


## as 계열

- 다른 데이터 타입을 가져와서 바꿔서 사용할 때는 as라는 이름이 보통 붙는다.

In [37]:
# python의 list데이터 타입을 int ndarray로 변환
a = [1, 2, 3] # python의 list
print(type(a))
print(type(a[0]))
b = np.array(a)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [41]:
# python의 list데이터 타입을 float ndarray로 변환
a = [1, 2, 3] # python의 list
print(type(a))
print(type(a[0]))
b = np.asfarray(a)
print(type(b))
print(type(b[0]))
print(b)

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
[1. 2. 3.]


In [40]:
# python의 list데이터 타입이 float이면 float ndarray로 변환
# python의 list데이터 타입이 int이면 int ndarray로 변환
a = [1., 2., 3.]
print(type(a))
print(type(a[0]))

b = np.asarray(a)
print(type(b))
print(type(b[0]))

c = np.array(a)
print(type(c))
print(type(c[0]))

<class 'list'>
<class 'float'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


## 값 가져오기

### comma로 값 가져오기

In [42]:
a = [[1, 2, 3], [4, 5, 6]] # python
b = np.array([[1, 2, 3], [4, 5, 6]]) # numpy

# 1차원 리스트로 가져온다.
a[0]

[1, 2, 3]

In [43]:
a[0, 1]

TypeError: ignored

python은 slice 함수를 이용해서 comma를 사용하는 방법은 가능하다.

In [44]:
# 2차원 리스트로 가져온다.
a[slice(0, 1)] # 0행부터 1행 미만의 데이터를 가져온다.

[[1, 2, 3]]

In [45]:
a[slice(0, 2)] # 0행부터 2행 미만의 데이터를 가져온다.

[[1, 2, 3], [4, 5, 6]]

In [47]:
a[0:2]

[[1, 2, 3], [4, 5, 6]]

numpy는 기본적으로 인덱싱 / 슬라이싱을 할 때 comma를 사용할 수 있다.

In [50]:
# b[행, 열]
print(b[0, 2])
print(b[0, -1])

3
3


In [51]:
# python
# a[행][열]
print(a[0][2])
print(a[0][-1])

3
3


### boolean indexing

numpy에서 boolean indexing 조건

- array만 가능하다.

- numpy True, False로만 가능하다.

- shape이 맞아야 한다.(개수가 맞을 때만 사용할 수 있다.)

- python에서는 지원하지 않는다.

In [52]:
a = [[1, 2, 3, 4]] # python list
a > 3 # TypeError

TypeError: ignored

In [55]:
b = np.array([1, 2, 3, 4])
b

array([1, 2, 3, 4])

array를 scalar와 연산하면 elementwise로 계산한다.  
(elementwise : 원소별로 각각 계산이 된다.)

In [56]:
# 원소별로 비교해서 True / False 로 계산한다. 
# 1 > 2, 2 > 2, 3 > 2, 4 > 2

# numpy에서는 가능하고 python에서는 안된다.
b > 2

array([False, False,  True,  True])

numpy는 indexing, slice 자리에 조건도 쓸 수 있다.  

True에 해당되는 값만 가져온다.

In [57]:
# boolean indexing
b[np.array([False, False, True, True])]

array([3, 4])

In [58]:
b[b > 2]

array([3, 4])

In [59]:
a = [1, 2, 3, 4]
a[True, True, False, False]

TypeError: ignored

### fancy indexing

In [60]:
# reshape 모양을 바꿀 때 사용한다.
b = np.arange(100).reshape(20, 5) # 20행 5열로 모양을 바꾼다.
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

인데싱, 슬라이싱 자리에 괄호를 하나 삽입하면 fancy indexing을 적용 할 수 있다.

여러개를 한 번에 인덱싱 할 수 있다.

In [66]:
b[:] # 전체를 가져온다. b[:, :]와 같다.
print(b[0, :]) # 0번째의 행을 전부 가져온다.
# b[행, 열]
print(b[1:3]) # 1행부터 3행 미만의 데이터를 가져온다.
print(b[1:3, 2:4]) # 1행부터 3행 미만이면서 2열부터 4열 미만의 데이터를 가져온다.
print((b[[1, 3, 5]])) # b[[1, 3, 5], :] 1행, 3행, 5행의 데이터를 가져온다.
print(b[[1, 3, 5], [0, 2, 4]]) # 1행 1열(0인덱스), 3행 3열(2인덱스), 5행 5열(4인덱스)의 데이터를 가져온다.

[0 1 2 3 4]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 7  8]
 [12 13]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[ 5 17 29]


fancying indexing은 인덱싱 기법만 사용할 수 있다.

' : ' (콜론)은 슬라이싱 기법이므로 지원하지 않는다.


In [67]:
b[[2 : 5]]

SyntaxError: ignored

In [68]:
# 갯수가 같게 지정되어야 한다.
b[[1, 3, 4], [0, 2, 1]]

array([ 5, 17, 21])

In [70]:
b[[1, 3, 4,], [0, 2]] # IndexError

IndexError: ignored