<a href="https://colab.research.google.com/github/eoooomji/home_python/blob/master/python_10_%ED%8C%8C%EC%9D%BCread%26write.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# 경로 변경
%cd '/content/drive/MyDrive/home_python'

/content/drive/MyDrive/home_python


In [4]:
!pwd

/content/drive/MyDrive/home_python


In [5]:
!ls

 python_01.ipynb	      python_07_numpy.ipynb
 python_02_statement.ipynb    python_08_numpy.ipynb
 python_03_function.ipynb     python_09_numpy.ipynb
 python_04_class.ipynb	      python_10_colab_환경설정.ipynb
 python_05_파일입출력.ipynb  'python_10_파일read&write.ipynb'
 python_06_정규표현식.ipynb


In [6]:
%%writefile ./example.txt
안녕
안녕안해

Writing ./example.txt


In [7]:
open('./example.txt')

<_io.TextIOWrapper name='./example.txt' mode='r' encoding='UTF-8'>

## 1. python

### open( '파일경로', '모드' )

- 모드

  (1) w : 쓰기모드 - 파일에 내용을 쓸 때

  (2) r : 읽기모드 - 파일에 내용을 읽을 때

  (3) a : 추가모드 - 파일에 내용을 추가할 때

- 파일의 형태 2가지

  (1) 사람 기준(txt)

  (2) 기계 기준(binary)
  

In [8]:
# wb : wrtie binary
# 쓰기모드로 파일을 불러오며, binary로 저장한다는 의미
a = open('./test.txt', 'wb')

In [9]:
# 'hello'의 타입은 str이므로 저장할 수 없다.
# binary로 설정이 되어 있기 때문에
a.write('hello')

TypeError: ignored

In [10]:
a.write(b'hello')

5

In [11]:
a.close()

저장한 test.txt 파일 읽어오기

In [25]:
b = open('./test.txt')

In [26]:
next(b)

'hello'

In [27]:
b.close()

### with

- with 구문은 시작할 때 enter, 종료할때 __exit를 자동으로 실행한다.

- exit가 실행되었기 때문에 close( )를 작성 안해도 된다.

- write가 끝난 후 write( )를 하면 'write to closed file' 에러가 발생한다.

In [15]:
with open('./test2.txt', 'wb') as c :
  c.write(b'aaa')
  c.write(b'bbb')

In [16]:
# 이미 종료가 되어 빠져나와서 더 이상 작성이 안된다.
c.write(b'ccc')

ValueError: ignored

In [17]:
with open('./test2.txt') as c :
  print(c.read())

aaabbb


## 2. numpy

- 자체적으로 저장과 불러오는 기능을 지원한다.

In [28]:
import numpy as np

In [29]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

numpy의 데이터를 파일에 저장한다.

ndata.npy로 저장된다.

array 객체 하나는 save( )로 저장할 수 있다.

확장자는 자동으로 npy가 붙는다.

In [30]:
np.save('./ndata1', a)

numpy의 파일을 읽어온다.

읽어올 때는 npy확장자를 붙여서 읽어와야 한다.

load( )를 사용하면 된다.

In [32]:
# b = np.load('./ndata1') 확장자 없이 불러오게 되면 오류가 발생
b = np.load('./ndata1.npy')
b

array([0, 1, 2, 3, 4])

In [33]:
print(type(b))

<class 'numpy.ndarray'>


savez는 여러개의 array를 저장할 수 있다.
확장자는 자동으로 npz가 붙는다.

In [34]:
b = np.array([1, 2, 3, 4, 5])
c = np.array([6, 7, 8, 9, 10])

In [35]:
np.savez('./ndata2', b, c)

In [37]:
d = np.load('./ndata2.npz')
d

In [39]:
print(type(d))
print(dir(d))

<class 'numpy.lib.npyio.NpzFile'>
['__abstractmethods__', '__class__', '__contains__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__enter__', '__eq__', '__exit__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_files', 'allow_pickle', 'close', 'f', 'fid', 'files', 'get', 'items', 'iteritems', 'iterkeys', 'keys', 'pickle_kwargs', 'values', 'zip']


diction 방식으로 저장된 객체를 가져올 수 있다.

In [40]:
d.files

['arr_0', 'arr_1']

In [41]:
print(d['arr_0'])
print(d['arr_1'])

[1 2 3 4 5]
[ 6  7  8  9 10]


## pandas

In [42]:
import pandas as pd

In [44]:
num = np.array([[1, 2, 3], [4, 5, 6]])
my_df = pd.DataFrame(num)
my_df

0  1  2
0  1  2  3
1  4  5  6

In [45]:
# pandas에 데이터 저장
my_df.to_csv('./ndata.csv', sep = '.')

In [46]:
# pandas에서 데이터 읽어오기
a = pd.read_csv('./ndata.csv', header = None)
a

0
0   .0.1.2
1  0.1.2.3
2  1.4.5.6