<a href="https://colab.research.google.com/github/eoooomji/home_python/blob/master/python_09_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## matrix

- numpy에서는 ndarray이외에 matrix라는 자료형도 존재한다.

- matrix에서는 * (곱하기) 연산자는 행렬곱을 의미한다.

In [2]:
type(np.array(3))

numpy.ndarray

In [3]:
c = np.matrix([[1, 2], [3, 4]])
c

matrix([[1, 2],
        [3, 4]])

In [4]:
type(c)

numpy.matrix

행렬 곱
```
a  b    *   a  b    =   (a*a)+(b*c)  (a*b)+(b*d)
c  d        c  d        (c*a)+(d*c)  (c*b)+(d*d)

```

In [5]:
# matrix * matrix = 행렬곱
c * c

matrix([[ 7, 10],
        [15, 22]])

ndarray에서 행렬곱 연산자는 @dlek.

python재단에서 numpy를 위해 만들어준 연산자이다.

In [19]:
a = np.arange(6).reshape(2, 3)
a
a.shape

(2, 3)

In [14]:
b = np.arange(1, 13).reshape(3, 4)
b
b.shape

(3, 4)

In [15]:
a @ b

ValueError: ignored

행렬곱을 하기 위해서는 shape가 맞아야 한다.

T = tranpse(전치)의 약자이다.

In [21]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
# 전치 행렬 : 행과 열을 바꾼다.
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

matrix는 @ 와 * 모두가 가능하다.

In [22]:
c @ c.T

matrix([[ 5, 11],
        [11, 25]])

In [23]:
c * c.T

matrix([[ 5, 11],
        [11, 25]])

함수 방법으로 np.dot( )을 사용할 수 있다.

In [24]:
np.dot(a, a.T) # ndarray

array([[ 5, 14],
       [14, 50]])

In [25]:
np.dot(c, c.T) # matrix

matrix([[ 5, 11],
        [11, 25]])

## broadcasting

- python은 배열과 숫자간에 연산을 할 수있다.

In [26]:
[1, 2, 3] + 1

TypeError: ignored

[1, 2, 3] + 1 => (x)  

[1, 2, 3] + [1, 2, 3] => (o) 연결  

[1, 2, 3] * 1 => (o) 반복  

[1, 2, 3] * [1, 2, 3] => (x)  

In [27]:
a = np.arange(6).reshape(2, 3) # ndarray
a

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
a + 1

array([[1, 2, 3],
       [4, 5, 6]])

broadcasting이랑 모양(shape)이 안맞아도 특정 조건에 성립하면 모양을 같게 만들어 연산을 해주는 기능이다.

위 연산에서 1을 a와 같은 모양으로 만들어 준다.
```
a + 1 
=> [[1, 1, 1],
    [1, 1, 1]]
```


### 1. broadcasting이 안되는 경우와 가능한 경우

In [29]:
a # 2행 3열

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
a + np.array([3, 4])

ValueError: ignored

In [31]:
a + np.array([3, 4, 5])

array([[ 3,  5,  7],
       [ 6,  8, 10]])

In [32]:
# broadcasting으로 인해  2행 3열로 바뀌어 계산이 된다.
# [1, 1, 1]
# [2, 2, 2]
# 위처럼 바뀌어 더하기가 된다.
a + np.array([[1], [2]])

array([[1, 2, 3],
       [5, 6, 7]])

## strides 

- strides는 다음 원소끼리의 메모리 크기를 차원별로 알려준다.

- c의 포인터 개념을 알고 있으면 이해하기가 쉽다.

In [40]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
# 행의 메모리 간격은 32bytes
# 열의 메모리 간격은 8bytes
a.strides

(32, 8)

In [35]:
a.dtype

dtype('int64')

In [36]:
a.itemsize

8

In [42]:
# 열의 원소 개수 * itemsize = 행의 메모리 간격
# itemsize = 열의 메모리 간격
a.shape

(3, 4)

## axis

- axis는 다차원 배열을 연산할 때 기준이 되는 축이다.
```
(0, 0), (0, 1), (0, 2), (0, 3)  
(1, 0), (1, 1), (1, 2), (1, 3)  
(2, 0), (2, 1), (2, 2), (2, 3)
```

In [43]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
np.sum(a)

66

In [45]:
# a배열은 2차원이므로 axis = 0 은 행 기준(행마다)을 의미한다.
np.sum(a, axis = 0)

array([12, 15, 18, 21])

In [46]:
# a배열은 2차원 이므로 axis = 1 은 열 기준(열마다)을 의미한다.
np.sum(a, axis = 1)

array([ 6, 22, 38])

axis는 3차원 이상에서도 사용할 수 있다.

3차원은 행렬에 공간(깊이) 개념이 추가되었다고 할 수 있다.

2차원(axis = 0, axis = 1) (행, 열)

3차원(axis = 0, axis = 1, axis = 2) (공간, 행, 열)

```
(0, 0, 0), (0, 0, 1), (0, 0, 2), (0, 0, 3)
(0, 1, 0), (0, 1, 1), (0, 1, 2), (0, 1, 3)
(0, 2, 0), (0, 2, 1), (0, 2, 2), (0, 2, 3)

(1, 0, 0), (1, 0, 1), (1, 0, 2), (1, 0, 3)
(1, 1, 0), (1, 1, 1), (1, 1, 2), (1, 1, 3)
(1, 2, 0), (1, 2, 1), (1, 2, 2), (1, 2, 3)
```

In [49]:
a = np.arange(24).reshape(2, 3, 4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [50]:
# 공간 기준(공간 마다)
np.sum(a, axis = 0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [51]:
# 행 기준(행 마다)
np.sum(a, axis = 1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [52]:
# 열 기준(열 마다)
np.sum(a, axis = 2)

array([[ 6, 22, 38],
       [54, 70, 86]])

## array 모양 바꾸기

### 1. reshape

- reshape은 차원을 바꿔주는 기능을 한다.

In [53]:
# signature 대로 하면 a.reshpae((3, 8))로 작성해야 한다.
# 하지만 reshape(3, 8)로 작성을 해도 내부적으로 이상 없이 처리한다.
# reshape 수행 후의 값은 그대로 있다.

a = np.arange(24).reshape(3, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [55]:
a = np.arange(24)
b = a.reshape(3, 8)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [56]:
a = np.arange(24).reshape(3, 8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [57]:
a.reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [58]:
# 크기가 맞이 않아 오류 발생
a.reshape(2, 3, 5)

ValueError: ignored

In [59]:
# 음수를 쓰면 알아서 shape을 맞춘다.
# 음수의 크기는 상관 없다.
a.reshape(2, 3, -1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [60]:
# 음수는 2개를 사용할 수 없다.
# 음수는 다른 차원들이 정해준 상황에서 남은 하나의 차원만 알아서 맞춰준다.
a.reshape(3, -1, -1)

ValueError: ignored

In [61]:
a.reshape(3, -1, 8)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]]])

### 2. reshape으로 차원 늘리기

In [62]:
# 2차원
a = np.arange(6).reshape(2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
# 3차원
a = np.arange(6).reshape(2, 3, 1)
a

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

## resize

- size는 원소 개수를 알려준다.

- reshape과의 차이점
  1. mutable이다. return이 없고 자기 자신을 바꾼다.

  2. 원래의 원소 개수와 변경하는 원소의 개수가 안맞아도 된다.(0으로 채워준다.)

In [65]:
a = np.arange(24)
# 원소의 개수
print(a.size)
print(len(a))
a

24
24


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [67]:
# a.resize(2, 3, 1)
np.resize(a, (2, 3, 1))

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [68]:
a.reshape(2, 3, 1) # 원소의 개수가 맞이 않음

ValueError: ignored

In [71]:
# 빈 공간은 0으로 채워줌
b = np.arange(24)
# b.resize(2, 3, 8)
b.resize((2, 3, 8))
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])

## array 나누기

### split

In [80]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [82]:
# a는 바뀌지 않으므로 재할당한다.
a = np.split(a, 3, axis = 0)
a

[array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21, 22, 23])]

In [83]:
print(type(a))
print(type(a[0]))

<class 'list'>
<class 'numpy.ndarray'>


In [84]:
b = np.arange(24)
b = np.split(b, 2)
b

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [90]:
print(type(b))
print(type(b[1]))
print(b[1])
print(b[1][2]) # list
# print(b[1, 2]) TypeError > array

c = np.array(b)
print(c)
print(type(c))
print(c[1, 2])

<class 'list'>
<class 'numpy.ndarray'>
[12 13 14 15 16 17 18 19 20 21 22 23]
14
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
<class 'numpy.ndarray'>
14


### hsplit & vsplit

- split은 axis 파라미터가 있다. (default : axis = 0)

In [91]:
a = np.arange(24)
b = a.reshape(4, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [92]:
np.split(b, 2, axis = 0)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [95]:
np.split(b, 2, axis = 1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [96]:
# horizontal(수평)
np.hsplit(a, 2)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

```
(0, 0) (0, 1) (0, 2) (0, 3) (0, 4) (0, 5)
(1, 0) (1, 1) (1, 2) (1, 3) (1, 4) (1, 5)
(2, 0) (2, 1) (2, 2) (2, 3) (2, 4) (2, 5)
(3, 0) (3, 1) (3, 2) (3, 3) (3, 4) (3, 5)
```

In [97]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [101]:
np.hsplit(b, 2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [98]:
# 2차원 일떄 vertical(수직)
# vsplit은 1차원일 때 valueError가 발생한다.
np.vsplit(b, 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

### indices_or_sections

- split 시리즈 함수들의 두 번째 파라미터 이름

- 숫자를 묶어서 넣으면 구간으로 나뉘다.

In [102]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [103]:
# section
# 처음부터 ~ 2미만 : [0, 1]
# 2부터 3미만 : [2]
# 3부터 끝까지 : [3, 4, 5...]
np.hsplit(a, (2, 3))

[array([0, 1]),
 array([2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23])]

In [104]:
# section
# 처음부터 2미만 : [0, 1]
# 2부터 3미만 : [2]
# 3부터 8미만 : [3, 4, 5, 6, 7]
# 8부터 끝까지 : [8, 9, 10...]
np.hsplit(a, (2, 3, 8))

[array([0, 1]),
 array([2]),
 array([3, 4, 5, 6, 7]),
 array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

## array 합치기 

In [107]:
a = np.arange(24)
x, y, z = np.split(a, 3)

In [108]:
print(x)
print(y)
print(z)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


### hstack & vstack

- hstack은 horizontal(가로)로 합쳐준다.

- vstack은 vertical(세로)로 합쳐준다.

In [109]:
np.hstack((x, y))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [110]:
np.vstack((x, y))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

### dstack

- dstack은 합쳐서 3차원으로 만들어 준다.

- 합칠 array들은 1차원, 2차원일 경우 차원을 눌린 후 합친다.

- 합쳐지는 차원은 axis = 2 이다.


In [112]:
x. shape

(8,)

In [113]:
y.shape

(8,)

In [115]:
c = np.dstack((x))
c

array([[[0, 1, 2, 3, 4, 5, 6, 7]]])

In [116]:
# x는 shape이 1차원 이므로 (1, m, 1)인 3차원으로 변환한다.
# y는 shape이 1차원 이므로 (1, n, 1)인 3차원으로 변환한다. 
# 합쳐지는 차원은 axis = 2 이다.
c = np.dstack((x, y)) # (1, 8, 2)
c

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11],
        [ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [117]:
c.shape

(1, 8, 2)

### concatenate

- concatenate는 axis방향에 그대로 합쳐준다.  
  (stack은 axis 방향에 새로운 차원을 만들어 합쳐준다.)

In [122]:
a = np.arange(12).reshape(3, 4)
x, y = np.split(a, 2, axis = 1)

In [120]:
print(a)
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [123]:
# 원래 shape 크기 그대로 유지를 한다.
np.concatenate((x, y)) # axis = 0

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [ 2,  3],
       [ 6,  7],
       [10, 11]])

In [124]:
# shape 크기를 1개 증가해서 합친다.
np.stack((x, y))

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

## 차원 확장

- numpy는 차원을 확장하는 여러가지 방법이 있다.

### reshape

In [126]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### stack

In [127]:
# 3차원으로 확장
# tuple에 원소가 1개 있으면 차원만 확장시켜준다.
np.stack((a, ))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

### newaxis

- 인덱싱 할 때 np.newaxis를 쓰면 차원을 늘릴 수 있다.

In [128]:
a # 2차원

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
# a[np.newaxis]
a[np.newaxis, :, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [131]:
a[np.newaxis].shape

(1, 3, 4)

In [132]:
a[ :, np.newaxis, :]

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [133]:
a[ :, np.newaxis, :].shape

(3, 1, 4)

In [134]:
a[:, :, np.newaxis]

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [135]:
a[:, :, np.newaxis].shape

(3, 4, 1)

In [136]:
np.newaxis is None

True

np.newaxis 대신에 None을 써도 된다.

None은 직관적이지 않고 헷갈려서 np.newaxis를 만들었다.

numpy를 만들 때 python의 모든 연산자를 다 사용해서 남는 연산자가 없었다.
그래서 None을 이용했다.

### expand_dims

In [137]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [138]:
# 공간이 늘어난다.
np.expand_dims(a, 0) # a[np.newaxis, :, :] 와 같다.

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [139]:
a[np.newaxis, :, :]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [140]:
np.expand_dims(a, 1) # a[:, np.newaxis, :] 와 같다.

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [141]:
np.expand_dims(a, 2) # a[:, :, np.newaxis] 와 같다.

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

## array 한 줄로 펴기

### flatten

In [142]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [143]:
# flatten()은 결과를 return하고 메모리의 값은 변경되지 않는다.
b = a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [146]:
print(a is b)
print(a == b)
print(id(a))
print(id(b))

False
False
140077757749648
140077757749264


<ipython-input-146-678a9f35dda2>:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(a == b)


## 서로 차원 교환


### swapaxes
- 행과 열이 바뀐다.

In [147]:
a = np.array([[1], [2]]) # 2차원 2행 1열
a

array([[1],
       [2]])

In [148]:
a.shape

(2, 1)

In [150]:
b = np.swapaxes(a, 1, 0)
b

array([[1, 2]])

In [151]:
b.shape

(1, 2)

In [152]:
a.T

array([[1, 2]])

In [153]:
a

array([[1],
       [2]])